---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - "VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}"
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - "SERVER_REGIONS=${SERVER_REGIONS}"
      - VPN_PORT_FORWARDING=on
    volumes:
      - ./volumes/gluetun:/tmp/gluetun
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    environment:
      - WEBUI_PORT=8080 # If you change this port, be sure to update the qbHostname variable accordingly in your .env file
      - UMASK=022
    volumes:
      - ./volumes/qbit:/config
  gluetun-qbit-port:
    build:
      context: .
    network_mode: "service:gluetun"
    depends_on:
      - qbittorrent
    init: true
    restart: on-failure
    user: 1000:1000 # You can set to run as any user. If you're having issues, might need to run as root
    environment:
      - qbUsername=${qbUsername} # qBittorrent web UI username
      - qbPassword=${qbPassword} # qBittorrent web UI password
      - TZ=${TZ} # Use your machine's current time zone for the container's logs
      # - qbHostname=http://qbittorrent-url:8080 # If you aren't running this container behind Gluetun, set this to however the container should access qBit
      # - gtHostname=http://gluetun-url:8000 # Same thing for Gluetun - don't change these if you are using {{ network_mode: "service:gluetun" }}
      # - qbHostname=${qbHostname} # Defaults to http://localhost:8000 - if you're attaching this container to Gluetun, don't change this
      # - logLevel=DEBUG # Defaults to INFO. Possible values are ERROR, INFO, and DEBUG with each level being progressively noisier
      # - sleepTime=1800 # Defaults to 30 minutes. This is how long the container will wait before re-running the check
